name: Check quality and unit tests

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, review_requested]
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Étape 2 : Configuration de l'environnement Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Étape 4 : Vérification du style avec flake8
      - name: Run flake8 lint
        uses: py-actions/flake8@v2
      
      # Étape 5 : Exécution des tests unitaires
      - name: Run unit tests
        run: pytest
